---
- name: installing http package and service start
  become: yes
  hosts: all
  tasks:
  - name: installing http package
    yum:
      name: httpd 
      state: present
  - name: starting httpd service
    service:
      name: httpd
      state: started
